apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-mysqldb
  name: db-lb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: ashu-mysqldb
  type: ClusterIP # only gonna create local LB to k8s 
status:
  loadBalancer: {}