apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-web
  name: ashu-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashu-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-web
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        ports:
        - containerPort: 80
        env: # using ENV to connect Db 
        - name: WORDPRESS_DB_HOST 
          valueFrom: # reading value of DB host from ConfigMAP 
            configMapKeyRef:
              name: ashu-app-connect
              key: dbconn
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: ashu-app-db
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: ashu-app-db
              key:  MYSQL_PASSWORD
        resources: {}
status: {}
